In [1]:
import pandas as pd
df = pd.read_csv(r"C:\Users\chari\Desktop\Future_Interns\FUTURE_ML_01\data\raw\train.csv")
df.head()

   id        date  store_nbr      family  sales  onpromotion
0   0  2013-01-01          1  AUTOMOTIVE    0.0            0
1   1  2013-01-01          1   BABY CARE    0.0            0
2   2  2013-01-01          1      BEAUTY    0.0            0
3   3  2013-01-01          1   BEVERAGES    0.0            0
4   4  2013-01-01          1       BOOKS    0.0            0

In [2]:
df.shape

(3000888, 6)

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000888 entries, 0 to 3000887
Data columns (total 6 columns):
 #   Column       Dtype
---  ------       -----
 0   id           int64
 1   date         object
 2   store_nbr    int64
 3   family       object
 4   sales        float64
 5   onpromotion  int64
dtypes: float64(1), int64(3), object(2)
memory usage: 137.4+ MB

In [4]:
df['store_nbr'].nunique()

54

In [5]:
df['family'].nunique()

33

In [6]:
df['date'] = pd.to_datetime(df['date'])

df['year'] = df['date'].dt.year
df['month'] = df['date'].dt.month
df['day'] = df['date'].dt.day
df['dayofweek'] = df['date'].dt.dayofweek

df.head()

,id,date,store_nbr,family,sales,onpromotion,year,month,day,dayofweek
0,0,2013-01-01,1,AUTOMOTIVE,0.0,0,2013,1,1,1
1,1,2013-01-01,1,BABY CARE,0.0,0,2013,1,1,1
2,2,2013-01-01,1,BEAUTY,0.0,0,2013,1,1,1
3,3,2013-01-01,1,BEVERAGES,0.0,0,2013,1,1,1
4,4,2013-01-01,1,BOOKS,0.0,0,2013,1,1,1

In [7]:
stores = pd.read_csv(r"C:\Users\chari\Desktop\Future_Interns\FUTURE_ML_01\data\raw\stores.csv")
stores.head()

   store_nbr           city                           state type  cluster
0          1          Quito                       Pichincha    D       13
1          2          Quito                       Pichincha    D       13
2          3          Quito                       Pichincha    D        8
3          4          Quito                       Pichincha    D        9
4          5  Santo Domingo  Santo Domingo de los Tsachilas    D        4

In [8]:
stores.shape

(54, 5)

In [9]:
stores.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54 entries, 0 to 53
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   store_nbr  54 non-null     int64
 1   city       54 non-null     object
 2   state      54 non-null     object
 3   type       54 non-null     object
 4   cluster    54 non-null     int64
dtypes: int64(2), object(3)
memory usage: 2.2+ KB

In [10]:
df = df.merge(stores, on='store_nbr', how='left')

In [11]:
df.head()

,id,date,store_nbr,family,sales,onpromotion,year,month,day,dayofweek,city,state,type,cluster
0,0,2013-01-01,1,AUTOMOTIVE,0.0,0,2013,1,1,1,Quito,Pichincha,D,13
1,1,2013-01-01,1,BABY CARE,0.0,0,2013,1,1,1,Quito,Pichincha,D,13
2,2,2013-01-01,1,BEAUTY,0.0,0,2013,1,1,1,Quito,Pichincha,D,13
3,3,2013-01-01,1,BEVERAGES,0.0,0,2013,1,1,1,Quito,Pichincha,D,13
4,4,2013-01-01,1,BOOKS,0.0,0,2013,1,1,1,Quito,Pichincha,D,13

In [12]:
df.shape

(3000888, 14)

In [13]:
transactions = pd.read_csv(r"C:\Users\chari\Desktop\Future_Interns\FUTURE_ML_01\data\raw\transactions.csv")
transactions.head()

         date  store_nbr  transactions
0  2013-01-01         25           770
1  2013-01-02          1          2111
2  2013-01-02          2          2358
3  2013-01-02          3          3487
4  2013-01-02          4          1922

In [14]:
transactions.shape

(83488, 3)

In [15]:
transactions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 83488 entries, 0 to 83487
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   date          83488 non-null  object
 1   store_nbr     83488 non-null  int64
 2   transactions  83488 non-null  int64
dtypes: int64(2), object(1)
memory usage: 1.9+ MB

In [16]:
transactions['date'] = pd.to_datetime(transactions['date'])

In [17]:
df = df.merge(transactions, on=['date', 'store_nbr'], how='left')

In [19]:
df.head()

,id,date,store_nbr,family,sales,onpromotion,year,month,day,dayofweek,city,state,type,cluster,transactions
0,0,2013-01-01,1,AUTOMOTIVE,0.0,0,2013,1,1,1,Quito,Pichincha,D,13,NaN
1,1,2013-01-01,1,BABY CARE,0.0,0,2013,1,1,1,Quito,Pichincha,D,13,NaN
2,2,2013-01-01,1,BEAUTY,0.0,0,2013,1,1,1,Quito,Pichincha,D,13,NaN
3,3,2013-01-01,1,BEVERAGES,0.0,0,2013,1,1,1,Quito,Pichincha,D,13,NaN
4,4,2013-01-01,1,BOOKS,0.0,0,2013,1,1,1,Quito,Pichincha,D,13,NaN

In [20]:
df.shape

(3000888, 15)

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000888 entries, 0 to 3000887
Data columns (total 15 columns):
 #   Column        Dtype
---  ------        -----
 0   id            int64
 1   date          datetime64[ns]
 2   store_nbr     int64
 3   family        object
 4   sales         float64
 5   onpromotion   int64
 6   year          int32
 7   month         int32
 8   day           int32
 9   dayofweek     int32
 10  city          object
 11  state         object
 12  type          object
 13  cluster       int64
 14  transactions  float64
dtypes: datetime64[ns](1), float64(2), int32(4), int64(4), object(4)
memory usage: 297.6+ MB

In [24]:
df['transactions'].isnull().sum()

np.int64(0)

In [23]:
df['transactions'] = df.groupby('store_nbr')['transactions'].ffill()
df['transactions'] = df['transactions'].fillna(0)

In [25]:
oil = pd.read_csv(r"C:\Users\chari\Desktop\Future_Interns\FUTURE_ML_01\data\raw\oil.csv")
oil.head()

         date  dcoilwtico
0  2013-01-01         NaN
1  2013-01-02       93.14
2  2013-01-03       92.97
3  2013-01-04       93.12
4  2013-01-07       93.20

In [33]:
oil = oil.set_index('date')

In [34]:
full_dates = pd.date_range(start=oil.index.min(), end=oil.index.max())

In [35]:
oil = oil.reindex(full_dates)

In [36]:
oil['dcoilwtico'] = oil['dcoilwtico'].ffill()

In [37]:
oil = oil.reset_index().rename(columns={'index': 'date'})

In [38]:
df = df.merge(oil, on='date', how='left')

In [43]:
df['dcoilwtico'].isnull().sum()

np.int64(1782)

In [46]:
df['dcoilwtico'] = df['dcoilwtico'].ffill().bfill()

In [47]:
df['dcoilwtico'].isnull().sum()

np.int64(0)

In [ ]:
df.info()
df.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000888 entries, 0 to 3000887
Data columns (total 16 columns):
 #   Column        Dtype
---  ------        -----
 0   id            int64
 1   date          datetime64[ns]
 2   store_nbr     int64
 3   family        object
 4   sales         float64
 5   onpromotion   int64
 6   year          int32
 7   month         int32
 8   day           int32
 9   dayofweek     int32
 10  city          object
 11  state         object
 12  type          object
 13  cluster       int64
 14  transactions  float64
 15  dcoilwtico    float64
dtypes: datetime64[ns](1), float64(3), int32(4), int64(4), object(4)
memory usage: 320.5+ MB

(3000888, 16)

In [49]:
df.head()

,id,date,store_nbr,family,sales,onpromotion,year,month,day,dayofweek,city,state,type,cluster,transactions,dcoilwtico
0,0,2013-01-01,1,AUTOMOTIVE,0.0,0,2013,1,1,1,Quito,Pichincha,D,13,0.0,93.14
1,1,2013-01-01,1,BABY CARE,0.0,0,2013,1,1,1,Quito,Pichincha,D,13,0.0,93.14
2,2,2013-01-01,1,BEAUTY,0.0,0,2013,1,1,1,Quito,Pichincha,D,13,0.0,93.14
3,3,2013-01-01,1,BEVERAGES,0.0,0,2013,1,1,1,Quito,Pichincha,D,13,0.0,93.14
4,4,2013-01-01,1,BOOKS,0.0,0,2013,1,1,1,Quito,Pichincha,D,13,0.0,93.14

In [50]:
holidays = pd.read_csv(r"C:\Users\chari\Desktop\Future_Interns\FUTURE_ML_01\data\raw\holidays_events.csv")
holidays.head()

,date,type,locale,locale_name,description,transferred
0,2012-03-02,Holiday,Local,Manta,Fundacion de Manta,False
1,2012-04-01,Holiday,Regional,Cotopaxi,Provincializacion de Cotopaxi,False
2,2012-04-12,Holiday,Local,Cuenca,Fundacion de Cuenca,False
3,2012-04-14,Holiday,Local,Libertad,Cantonizacion de Libertad,False
4,2012-04-21,Holiday,Local,Riobamba,Cantonizacion de Riobamba,False

In [52]:
holidays.info() 
holidays.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 350 entries, 0 to 349
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         350 non-null    object
 1   type         350 non-null    object
 2   locale       350 non-null    object
 3   locale_name  350 non-null    object
 4   description  350 non-null    object
 5   transferred  350 non-null    bool
dtypes: bool(1), object(5)
memory usage: 14.1+ KB

(350, 6)

In [53]:
holidays['date'] = pd.to_datetime(holidays['date'])

In [54]:
holidays = holidays[holidays['transferred'] == False]

In [55]:
holidays['is_holiday'] = 1

In [56]:
holidays = holidays.groupby('date')['is_holiday'].max().reset_index()

In [57]:
df = df.merge(holidays, on='date', how='left')

In [58]:
df['is_holiday'] = df['is_holiday'].fillna(0)

In [59]:
df.head()

,id,date,store_nbr,family,sales,onpromotion,year,month,day,dayofweek,city,state,type,cluster,transactions,dcoilwtico,is_holiday
0,0,2013-01-01,1,AUTOMOTIVE,0.0,0,2013,1,1,1,Quito,Pichincha,D,13,0.0,93.14,1.0
1,1,2013-01-01,1,BABY CARE,0.0,0,2013,1,1,1,Quito,Pichincha,D,13,0.0,93.14,1.0
2,2,2013-01-01,1,BEAUTY,0.0,0,2013,1,1,1,Quito,Pichincha,D,13,0.0,93.14,1.0
3,3,2013-01-01,1,BEVERAGES,0.0,0,2013,1,1,1,Quito,Pichincha,D,13,0.0,93.14,1.0
4,4,2013-01-01,1,BOOKS,0.0,0,2013,1,1,1,Quito,Pichincha,D,13,0.0,93.14,1.0

In [60]:
# =========================
# LAG FEATURE ENGINEERING
# =========================

# 1. Sort data properly (CRITICAL for time-series)
df = df.sort_values(['store_nbr', 'family', 'date'])

# 2. Create lag features
df['lag_1'] = df.groupby(['store_nbr', 'family'])['sales'].shift(1)
df['lag_7'] = df.groupby(['store_nbr', 'family'])['sales'].shift(7)
df['lag_14'] = df.groupby(['store_nbr', 'family'])['sales'].shift(14)

# 3. Rolling mean features (STRONG features)
df['rolling_mean_7'] = df.groupby(['store_nbr', 'family'])['sales'].shift(1).rolling(7).mean()
df['rolling_mean_14'] = df.groupby(['store_nbr', 'family'])['sales'].shift(1).rolling(14).mean()

# 4. Rolling std (captures volatility)
df['rolling_std_7'] = df.groupby(['store_nbr', 'family'])['sales'].shift(1).rolling(7).std()

# 5. Check missing values (IMPORTANT)
lag_cols = ['lag_1', 'lag_7', 'lag_14', 'rolling_mean_7', 'rolling_mean_14', 'rolling_std_7']
print(df[lag_cols].isnull().sum())

# 6. Preview
df.head(10)

lag_1               1782
lag_7              12474
lag_14             24948
rolling_mean_7     12474
rolling_mean_14    24948
rolling_std_7      12474
dtype: int64

,id,date,store_nbr,family,sales,onpromotion,year,month,day,dayofweek,...,cluster,transactions,dcoilwtico,is_holiday,lag_1,lag_7,lag_14,rolling_mean_7,rolling_mean_14,rolling_std_7
0,0,2013-01-01,1,AUTOMOTIVE,0.0,0,2013,1,1,1,...,13,0.0,93.14,1.0,NaN,NaN,NaN,NaN,NaN,NaN
1782,1782,2013-01-02,1,AUTOMOTIVE,2.0,0,2013,1,2,2,...,13,2111.0,93.14,0.0,0.0,NaN,NaN,NaN,NaN,NaN
3564,3564,2013-01-03,1,AUTOMOTIVE,3.0,0,2013,1,3,3,...,13,1833.0,92.97,0.0,2.0,NaN,NaN,NaN,NaN,NaN
5346,5346,2013-01-04,1,AUTOMOTIVE,3.0,0,2013,1,4,4,...,13,1863.0,93.12,0.0,3.0,NaN,NaN,NaN,NaN,NaN
7128,7128,2013-01-05,1,AUTOMOTIVE,5.0,0,2013,1,5,5,...,13,1509.0,93.12,1.0,3.0,NaN,NaN,NaN,NaN,NaN
8910,8910,2013-01-06,1,AUTOMOTIVE,2.0,0,2013,1,6,6,...,13,520.0,93.12,0.0,5.0,NaN,NaN,NaN,NaN,NaN
10692,10692,2013-01-07,1,AUTOMOTIVE,0.0,0,2013,1,7,0,...,13,1807.0,93.20,0.0,2.0,NaN,NaN,NaN,NaN,NaN
12474,12474,2013-01-08,1,AUTOMOTIVE,2.0,0,2013,1,8,1,...,13,1869.0,93.21,0.0,0.0,0.0,NaN,2.142857,NaN,1.772811
14256,14256,2013-01-09,1,AUTOMOTIVE,2.0,0,2013,1,9,2,...,13,1910.0,93.08,0.0,2.0,2.0,NaN,2.428571,NaN,1.511858
16038,16038,2013-01-10,1,AUTOMOTIVE,2.0,0,2013,1,10,3,...,13,1679.0,93.81,0.0,2.0,3.0,NaN,2.428571,NaN,1.511858

In [61]:
df = df.dropna()
df = df.reset_index(drop=True)

In [62]:
df.isnull().sum()

id                 0
date               0
store_nbr          0
family             0
sales              0
onpromotion        0
year               0
month              0
day                0
dayofweek          0
city               0
state              0
type               0
cluster            0
transactions       0
dcoilwtico         0
is_holiday         0
lag_1              0
lag_7              0
lag_14             0
rolling_mean_7     0
rolling_mean_14    0
rolling_std_7      0
dtype: int64

In [63]:
df = df.drop(columns=['id'])

In [64]:
df = df.drop(columns=['date'])

In [65]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2975940 entries, 0 to 2975939
Data columns (total 21 columns):
 #   Column           Dtype
---  ------           -----
 0   store_nbr        int64
 1   family           object
 2   sales            float64
 3   onpromotion      int64
 4   year             int32
 5   month            int32
 6   day              int32
 7   dayofweek        int32
 8   city             object
 9   state            object
 10  type             object
 11  cluster          int64
 12  transactions     float64
 13  dcoilwtico       float64
 14  is_holiday       float64
 15  lag_1            float64
 16  lag_7            float64
 17  lag_14           float64
 18  rolling_mean_7   float64
 19  rolling_mean_14  float64
 20  rolling_std_7    float64
dtypes: float64(10), int32(4), int64(3), object(4)
memory usage: 431.4+ MB

In [179]:
df['is_weekend'] = df['dayofweek'].isin([5,6]).astype(int)
df['quarter'] = (df['month'] - 1)//3
df['is_month_start'] = (df['day'] <= 7).astype(int)
df['is_month_end'] = (df['day'] >= 25).astype(int)
df['week_of_year'] = df['date'].dt.isocalendar().week.astype(int)
df['day_of_year'] = df['date'].dt.dayofyear

In [180]:
df['promo_last_7'] = (
    df.groupby(['store_nbr','family'])['onpromotion']
      .shift(1)
      .rolling(7)
      .sum()
)

In [181]:
df['promo_x_transactions'] = df['onpromotion'] * df['transactions']
df['lag_ratio_7_1'] = df['lag_7'] / (df['lag_1'] + 1)
df = df.dropna()

In [182]:
df['rolling_median_7'] = (
    df.groupby(['store_nbr','family'])['sales']
      .shift(1)
      .rolling(7)
      .median()
)

In [183]:
df['momentum_7'] = df['lag_1'] - df['lag_7']

In [184]:
df['store_avg'] = df.groupby('store_nbr')['sales'].transform('mean')
df['sales_relative'] = df['lag_1'] / (df['store_avg'] + 1)

In [185]:
df['dow_avg'] = (
    df.groupby(['store_nbr','family','dayofweek'])['sales']
      .transform('mean')
)

In [186]:
df['promo_effect'] = (
    df['onpromotion'] * df['lag_7']
)

In [187]:
df['rolling_std_14'] = (
    df.groupby(['store_nbr','family'])['sales']
      .shift(1)
      .rolling(14)
      .std()
)

In [188]:
df.shape

(2926044, 38)

In [189]:
df['date'] = pd.to_datetime(df[['year','month','day']])

train = df[df['date'] < '2017-01-01']
test  = df[df['date'] >= '2017-01-01']

In [190]:
train = train.drop(columns=['date'])
test  = test.drop(columns=['date'])

In [191]:
X_train = train.drop('sales', axis=1)
y_train = train['sales']

X_test  = test.drop('sales', axis=1)
y_test  = test['sales']

In [192]:
import pandas as pd

X_train = pd.get_dummies(X_train)
X_test  = pd.get_dummies(X_test)

X_train, X_test = X_train.align(X_test, join='left', axis=1, fill_value=0)

In [193]:
from xgboost import XGBRegressor

model = XGBRegressor(
    n_estimators=500,
    learning_rate=0.03,
    max_depth=10,
    subsample=0.8,
    colsample_bytree=0.8,
    reg_alpha=0.2,
    reg_lambda=2,
    random_state=42,
    n_jobs=-1
)
model.fit(X_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=0.8, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.03, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=10,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=500,
             n_jobs=-1, num_parallel_tree=None, ...)

In [194]:
import numpy as np
from sklearn.metrics import mean_squared_error, mean_absolute_error

preds = model.predict(X_test)

rmse = np.sqrt(mean_squared_error(y_test, preds))
mae  = mean_absolute_error(y_test, preds)

print("RMSE:", rmse)
print("MAE:", mae)

RMSE: 242.52022172940417
MAE: 57.93723461313081

In [195]:
import pandas as pd

importance = pd.Series(model.feature_importances_, index=X_train.columns)
importance = importance.sort_values(ascending=False)

print(importance.head(10))

rolling_mean_7      0.630986
lag_7               0.124327
lag_14              0.041305
rolling_median_7    0.040330
lag_1               0.036132
rolling_mean_14     0.017973
dow_avg             0.006764
transactions        0.005577
is_month_start      0.005185
is_weekend          0.004927
dtype: float32

In [196]:
import pickle
import os

# create outputs folder if not exists
os.makedirs("outputs", exist_ok=True)

# save model
with open("outputs/xgboost_model.pkl", "wb") as f:
    pickle.dump(model, f)

print("Model saved successfully!")

Model saved successfully!

In [197]:
with open("outputs/feature_columns.pkl", "wb") as f:
    pickle.dump(X_train.columns.tolist(), f)