In [1]:
import pandas as pd
df = pd.read_csv(r"C:\Users\chari\Desktop\Future_Interns\FUTURE_ML_01\data\raw\train.csv")
df.head()

   id        date  store_nbr      family  sales  onpromotion
0   0  2013-01-01          1  AUTOMOTIVE    0.0            0
1   1  2013-01-01          1   BABY CARE    0.0            0
2   2  2013-01-01          1      BEAUTY    0.0            0
3   3  2013-01-01          1   BEVERAGES    0.0            0
4   4  2013-01-01          1       BOOKS    0.0            0

In [2]:
df.shape

(3000888, 6)

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000888 entries, 0 to 3000887
Data columns (total 6 columns):
 #   Column       Dtype
---  ------       -----
 0   id           int64
 1   date         object
 2   store_nbr    int64
 3   family       object
 4   sales        float64
 5   onpromotion  int64
dtypes: float64(1), int64(3), object(2)
memory usage: 137.4+ MB

In [4]:
df['store_nbr'].nunique()

54

In [5]:
df['family'].nunique()

33

In [6]:
df['date'] = pd.to_datetime(df['date'])

df['year'] = df['date'].dt.year
df['month'] = df['date'].dt.month
df['day'] = df['date'].dt.day
df['dayofweek'] = df['date'].dt.dayofweek

df.head()

,id,date,store_nbr,family,sales,onpromotion,year,month,day,dayofweek
0,0,2013-01-01,1,AUTOMOTIVE,0.0,0,2013,1,1,1
1,1,2013-01-01,1,BABY CARE,0.0,0,2013,1,1,1
2,2,2013-01-01,1,BEAUTY,0.0,0,2013,1,1,1
3,3,2013-01-01,1,BEVERAGES,0.0,0,2013,1,1,1
4,4,2013-01-01,1,BOOKS,0.0,0,2013,1,1,1

In [7]:
stores = pd.read_csv(r"C:\Users\chari\Desktop\Future_Interns\FUTURE_ML_01\data\raw\stores.csv")
stores.head()

   store_nbr           city                           state type  cluster
0          1          Quito                       Pichincha    D       13
1          2          Quito                       Pichincha    D       13
2          3          Quito                       Pichincha    D        8
3          4          Quito                       Pichincha    D        9
4          5  Santo Domingo  Santo Domingo de los Tsachilas    D        4

In [8]:
stores.shape

(54, 5)

In [9]:
stores.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54 entries, 0 to 53
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   store_nbr  54 non-null     int64
 1   city       54 non-null     object
 2   state      54 non-null     object
 3   type       54 non-null     object
 4   cluster    54 non-null     int64
dtypes: int64(2), object(3)
memory usage: 2.2+ KB

In [10]:
df = df.merge(stores, on='store_nbr', how='left')

In [11]:
df.head()

,id,date,store_nbr,family,sales,onpromotion,year,month,day,dayofweek,city,state,type,cluster
0,0,2013-01-01,1,AUTOMOTIVE,0.0,0,2013,1,1,1,Quito,Pichincha,D,13
1,1,2013-01-01,1,BABY CARE,0.0,0,2013,1,1,1,Quito,Pichincha,D,13
2,2,2013-01-01,1,BEAUTY,0.0,0,2013,1,1,1,Quito,Pichincha,D,13
3,3,2013-01-01,1,BEVERAGES,0.0,0,2013,1,1,1,Quito,Pichincha,D,13
4,4,2013-01-01,1,BOOKS,0.0,0,2013,1,1,1,Quito,Pichincha,D,13

In [12]:
df.shape

(3000888, 14)

In [13]:
transactions = pd.read_csv(r"C:\Users\chari\Desktop\Future_Interns\FUTURE_ML_01\data\raw\transactions.csv")
transactions.head()

         date  store_nbr  transactions
0  2013-01-01         25           770
1  2013-01-02          1          2111
2  2013-01-02          2          2358
3  2013-01-02          3          3487
4  2013-01-02          4          1922

In [14]:
transactions.shape

(83488, 3)

In [15]:
transactions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 83488 entries, 0 to 83487
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   date          83488 non-null  object
 1   store_nbr     83488 non-null  int64
 2   transactions  83488 non-null  int64
dtypes: int64(2), object(1)
memory usage: 1.9+ MB

In [16]:
transactions['date'] = pd.to_datetime(transactions['date'])

In [17]:
df = df.merge(transactions, on=['date', 'store_nbr'], how='left')

In [19]:
df.head()

,id,date,store_nbr,family,sales,onpromotion,year,month,day,dayofweek,city,state,type,cluster,transactions
0,0,2013-01-01,1,AUTOMOTIVE,0.0,0,2013,1,1,1,Quito,Pichincha,D,13,NaN
1,1,2013-01-01,1,BABY CARE,0.0,0,2013,1,1,1,Quito,Pichincha,D,13,NaN
2,2,2013-01-01,1,BEAUTY,0.0,0,2013,1,1,1,Quito,Pichincha,D,13,NaN
3,3,2013-01-01,1,BEVERAGES,0.0,0,2013,1,1,1,Quito,Pichincha,D,13,NaN
4,4,2013-01-01,1,BOOKS,0.0,0,2013,1,1,1,Quito,Pichincha,D,13,NaN

In [20]:
df.shape

(3000888, 15)

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000888 entries, 0 to 3000887
Data columns (total 15 columns):
 #   Column        Dtype
---  ------        -----
 0   id            int64
 1   date          datetime64[ns]
 2   store_nbr     int64
 3   family        object
 4   sales         float64
 5   onpromotion   int64
 6   year          int32
 7   month         int32
 8   day           int32
 9   dayofweek     int32
 10  city          object
 11  state         object
 12  type          object
 13  cluster       int64
 14  transactions  float64
dtypes: datetime64[ns](1), float64(2), int32(4), int64(4), object(4)
memory usage: 297.6+ MB

In [24]:
df['transactions'].isnull().sum()

np.int64(0)

In [23]:
df['transactions'] = df.groupby('store_nbr')['transactions'].ffill()
df['transactions'] = df['transactions'].fillna(0)

In [25]:
oil = pd.read_csv(r"C:\Users\chari\Desktop\Future_Interns\FUTURE_ML_01\data\raw\oil.csv")
oil.head()

         date  dcoilwtico
0  2013-01-01         NaN
1  2013-01-02       93.14
2  2013-01-03       92.97
3  2013-01-04       93.12
4  2013-01-07       93.20

In [33]:
oil = oil.set_index('date')

In [34]:
full_dates = pd.date_range(start=oil.index.min(), end=oil.index.max())

In [35]:
oil = oil.reindex(full_dates)

In [36]:
oil['dcoilwtico'] = oil['dcoilwtico'].ffill()

In [37]:
oil = oil.reset_index().rename(columns={'index': 'date'})

In [38]:
df = df.merge(oil, on='date', how='left')

In [43]:
df['dcoilwtico'].isnull().sum()

np.int64(1782)

In [46]:
df['dcoilwtico'] = df['dcoilwtico'].ffill().bfill()

In [47]:
df['dcoilwtico'].isnull().sum()

np.int64(0)

In [ ]:
df.info()
df.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000888 entries, 0 to 3000887
Data columns (total 16 columns):
 #   Column        Dtype
---  ------        -----
 0   id            int64
 1   date          datetime64[ns]
 2   store_nbr     int64
 3   family        object
 4   sales         float64
 5   onpromotion   int64
 6   year          int32
 7   month         int32
 8   day           int32
 9   dayofweek     int32
 10  city          object
 11  state         object
 12  type          object
 13  cluster       int64
 14  transactions  float64
 15  dcoilwtico    float64
dtypes: datetime64[ns](1), float64(3), int32(4), int64(4), object(4)
memory usage: 320.5+ MB

(3000888, 16)

In [49]:
df.head()

,id,date,store_nbr,family,sales,onpromotion,year,month,day,dayofweek,city,state,type,cluster,transactions,dcoilwtico
0,0,2013-01-01,1,AUTOMOTIVE,0.0,0,2013,1,1,1,Quito,Pichincha,D,13,0.0,93.14
1,1,2013-01-01,1,BABY CARE,0.0,0,2013,1,1,1,Quito,Pichincha,D,13,0.0,93.14
2,2,2013-01-01,1,BEAUTY,0.0,0,2013,1,1,1,Quito,Pichincha,D,13,0.0,93.14
3,3,2013-01-01,1,BEVERAGES,0.0,0,2013,1,1,1,Quito,Pichincha,D,13,0.0,93.14
4,4,2013-01-01,1,BOOKS,0.0,0,2013,1,1,1,Quito,Pichincha,D,13,0.0,93.14

In [50]:
holidays = pd.read_csv(r"C:\Users\chari\Desktop\Future_Interns\FUTURE_ML_01\data\raw\holidays_events.csv")
holidays.head()

,date,type,locale,locale_name,description,transferred
0,2012-03-02,Holiday,Local,Manta,Fundacion de Manta,False
1,2012-04-01,Holiday,Regional,Cotopaxi,Provincializacion de Cotopaxi,False
2,2012-04-12,Holiday,Local,Cuenca,Fundacion de Cuenca,False
3,2012-04-14,Holiday,Local,Libertad,Cantonizacion de Libertad,False
4,2012-04-21,Holiday,Local,Riobamba,Cantonizacion de Riobamba,False

In [52]:
holidays.info() 
holidays.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 350 entries, 0 to 349
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         350 non-null    object
 1   type         350 non-null    object
 2   locale       350 non-null    object
 3   locale_name  350 non-null    object
 4   description  350 non-null    object
 5   transferred  350 non-null    bool
dtypes: bool(1), object(5)
memory usage: 14.1+ KB

(350, 6)

In [53]:
holidays['date'] = pd.to_datetime(holidays['date'])

In [54]:
holidays = holidays[holidays['transferred'] == False]

In [55]:
holidays['is_holiday'] = 1

In [56]:
holidays = holidays.groupby('date')['is_holiday'].max().reset_index()

In [57]:
df = df.merge(holidays, on='date', how='left')

In [58]:
df['is_holiday'] = df['is_holiday'].fillna(0)

In [59]:
df.head()

,id,date,store_nbr,family,sales,onpromotion,year,month,day,dayofweek,city,state,type,cluster,transactions,dcoilwtico,is_holiday
0,0,2013-01-01,1,AUTOMOTIVE,0.0,0,2013,1,1,1,Quito,Pichincha,D,13,0.0,93.14,1.0
1,1,2013-01-01,1,BABY CARE,0.0,0,2013,1,1,1,Quito,Pichincha,D,13,0.0,93.14,1.0
2,2,2013-01-01,1,BEAUTY,0.0,0,2013,1,1,1,Quito,Pichincha,D,13,0.0,93.14,1.0
3,3,2013-01-01,1,BEVERAGES,0.0,0,2013,1,1,1,Quito,Pichincha,D,13,0.0,93.14,1.0
4,4,2013-01-01,1,BOOKS,0.0,0,2013,1,1,1,Quito,Pichincha,D,13,0.0,93.14,1.0